from pathlib import Path
import re

root = Path('.')
web = root / 'webui'
api_path = root / 'src' / 'api.rs'
assets_path = root / 'src' / 'webui_assets.rs'

if not (web / 'index.html').is_file() or not (web / 'app.js').is_file():
    raise SystemExit('webui/ was not copied from the Go repository')

# Go's handler injects these at request time. Rust serves embedded files directly,
# so materialize exactly the same rendered index during the sync step.
idx_path = web / 'index.html'
idx = idx_path.read_text(encoding='utf-8')
zh_button = '<button data-v="zh-CN" onclick="setLang(\'zh-CN\')">中文</button>'
if 'data-v="zh-TW"' not in idx and zh_button in idx:
    idx = idx.replace(
        zh_button,
        '<button data-v="zh-CN" onclick="setLang(\'zh-CN\')">简中</button>\n        '
        '<button data-v="zh-TW" onclick="setLang(\'zh-TW\')">繁中</button>',
        1,
    )
if 'src="zh-tw.js"' not in idx:
    idx = idx.replace(
        '</body>',
        '<script src="zh-tw.js"></script>\n'
        '<script src="frameviz.js"></script>\n'
        '<script src="frameviz-zh-tw.js"></script>\n'
        '</body>',
        1,
    )
idx_path.write_text(idx, encoding='utf-8')

# Build a zero-runtime-dependency embedded asset table. Every icon/favicon is
# compiled into the Rust executable, so WebUI rendering never depends on a CDN.
def content_type(path: Path) -> str:
    ext = path.suffix.lower()
    return {
        '.html': 'text/html; charset=utf-8',
        '.css': 'text/css; charset=utf-8',
        '.js': 'application/javascript; charset=utf-8',
        '.svg': 'image/svg+xml',
        '.ico': 'image/x-icon',
        '.png': 'image/png',
        '.webp': 'image/webp',
        '.json': 'application/json; charset=utf-8',
    }.get(ext, 'application/octet-stream')

files = sorted(p for p in web.rglob('*') if p.is_file())
match_lines = []
for p in files:
    rel = p.relative_to(web).as_posix()
    url = '/' + rel
    include_path = '../webui/' + rel
    ct = content_type(p)
    aliases = [url]
    if rel == 'index.html':
        aliases.insert(0, '/')
    if rel == 'login.html':
        aliases.insert(0, '/login')
    pat = ' | '.join(f'"{a}"' for a in aliases)
    match_lines.append(
        f'        {pat} => Some((include_bytes!("{include_path}"), "{ct}")),')

assets_path.write_text(
    '// Code-generated by the one-off WebUI parity migration.\n'
    '// Keep assets local and embedded; do not replace these with CDN URLs.\n\n'
    'pub fn asset(path: &str) -> Option<(&\'static [u8], &\'static str)> {\n'
    '    match path {\n'
    + '\n'.join(match_lines)
    + '\n        _ => None,\n'
    '    }\n'
    '}\n',
    encoding='utf-8',
)

api = api_path.read_text(encoding='utf-8')

# Remove the obsolete monolithic HTML/JS blob. The Go webui/ tree is now the
# authoritative frontend source and webui_assets.rs is the Rust embed layer.
start_marker = '// ======================= 面板（与 Go dashboardHTML 同源） ======================='
web_marker = '// ======================= Web 服务（Basic Auth + CSRF + API） ======================='
start = api.find(start_marker)
end = api.find(web_marker, start + 1) if start >= 0 else -1
if start >= 0 and end >= 0:
    api = (
        api[:start]
        + '// ======================= WebUI 静态资源（与 Go webui/ 同源） =======================\n\n'
        + '#[path = "webui_assets.rs"]\nmod webui_assets;\n\n'
        + api[end:]
    )
elif '#[path = "webui_assets.rs"]' not in api:
    raise SystemExit('could not locate legacy DASHBOARD_HTML block')

# Embedded frontend is served behind the same Basic Auth gate as the APIs.
needle = '        match (request.method(), url.as_str()) {'
asset_serve = '''        if request.method() == &Method::Get {
            if let Some((body, content_type)) = webui_assets::asset(url.as_str()) {
                let response = Response::from_data(body)
                    .with_header(http_header("Content-Type", content_type))
                    .with_header(http_header("Cache-Control", "no-store"));
                let _ = request.respond(response);
                continue;
            }
        }

'''
if 'webui_assets::asset(url.as_str())' not in api:
    if needle not in api:
        raise SystemExit('could not locate request route match')
    api = api.replace(needle, asset_serve + needle, 1)

# The old root arm refers to DASHBOARD_HTML; static serving above supersedes it.
root_arm = re.compile(
    r'\n\s*\(&Method::Get, "/"\) => \{.*?\n\s*\}\n\s*\(&Method::Get, "/api/stats"\) => \{',
    re.S,
)
api, n = root_arm.subn('\n            (&Method::Get, "/api/stats") => {', api, count=1)
if n == 0 and 'DASHBOARD_HTML' in api:
    raise SystemExit('legacy root DASHBOARD_HTML route was not removed')

# Go's modern frontend also probes trend/events/config. Rust does not yet keep
# Go's historical trend/event rings or support live config mutation, so expose
# explicit, well-formed compatibility responses instead of noisy 404s. This
# keeps the UI aligned while remaining truthful about unsupported mutations.
compat_marker = '            (&Method::Get, "/metrics") => {'
compat = '''            (&Method::Get, "/api/trend") => {
                respond_json(request, r#"{"step_sec":1,"points":[]}"#.to_string(), 200);
            }
            (&Method::Get, "/api/events") => {
                // EventSource receives JSON and closes; the Go frontend then falls back
                // to its polling path. Empty is the truthful state until Rust gets an
                // event ring equivalent to Go events.go.
                respond_json(request, "[]".to_string(), 200);
            }
            (&Method::Get, "/api/config") => {
                respond_json(request, ctx.cfg.to_string(), 200);
            }
            (&Method::Post, "/api/config") => {
                respond_json(
                    request,
                    json!({"error":"runtime config save/apply is not supported by the Rust backend yet"}).to_string(),
                    501,
                );
            }
'''
if '(&Method::Get, "/api/trend")' not in api:
    if compat_marker not in api:
        raise SystemExit('could not locate metrics route for compatibility routes')
    api = api.replace(compat_marker, compat + compat_marker, 1)

api_path.write_text(api, encoding='utf-8')

# Replace the legacy inline-dashboard parser test with an asset-contract test.
test = root / 'tests' / 'dashboard_script_test.rs'
test.write_text(r'''use std::fs;
use std::path::Path;

fn webui() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("webui")
}

#[test]
fn webui_matches_shared_static_asset_contract() {
    let root = webui();
    let index = fs::read_to_string(root.join("index.html")).expect("index.html");
    let app = fs::read_to_string(root.join("app.js")).expect("app.js");
    let css = fs::read_to_string(root.join("style.css")).expect("style.css");

    assert!(index.contains("/favicon.ico"), "missing local favicon link");
    assert!(index.contains("src=\"app.js\""), "index must load shared app.js");
    assert!(index.contains("data-v=\"zh-TW\""), "Rust rendered index must include Go's zh-TW injection");
    assert!(app.contains("platformAssetName"), "missing local OS/arch icon mapper");
    assert!(app.contains("/api/stats"), "dashboard must use stats API");
    assert!(css.contains("platform-badge"), "missing platform icon styles");

    for file in [
        "favicon.ico",
        "icons/os-linux.svg",
        "icons/os-windows.svg",
        "icons/os-macos.svg",
        "icons/os-android.svg",
        "icons/arch-x86_64.svg",
        "icons/arch-arm64.svg",
        "icons/arch-riscv64.svg",
    ] {
        let meta = fs::metadata(root.join(file)).unwrap_or_else(|e| panic!("missing {file}: {e}"));
        assert!(meta.len() > 0, "empty asset: {file}");
    }
}

#[test]
fn rust_embed_table_covers_primary_assets() {
    let src = fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR")).join("src/webui_assets.rs"),
    )
    .expect("webui_assets.rs");
    for route in ["/", "/index.html", "/style.css", "/app.js", "/favicon.ico", "/icons/os-linux.svg"] {
        assert!(src.contains(&format!("\"{route}\"")), "embed table missing {route}");
    }
}
''', encoding='utf-8')

# Guard against accidentally syncing a frontend that suddenly starts depending
# on new APIs without a Rust-side decision. Query strings are intentionally
# stripped by the regex result.
app = (web / 'app.js').read_text(encoding='utf-8')
endpoints = sorted(set(re.findall(r'/api/[A-Za-z0-9_-]+', app)))
allowed = {'/api/stats', '/api/logs', '/api/control', '/api/config', '/api/events', '/api/trend'}
unknown = sorted(set(endpoints) - allowed)
if unknown:
    raise SystemExit(f'Go WebUI introduced unsupported API endpoints: {unknown}')
print('WebUI API endpoints:', ', '.join(endpoints))
