import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const app=fs.readFileSync('webui/app.js','utf8');
const nodes={};let now=1000;
const ctx={performance:{now:()=>now},document:{getElementById:id=>nodes[id]||(nodes[id]={innerText:'',innerHTML:'',textContent:''})},rttStats:()=>null,dgRun:()=>({}),renderConnQuality:()=>{},renderConnsTable:()=>{},schedulerCell:()=>{},t:x=>x,chip:()=>'',fmtBytes:x=>String(x),fmtNum:x=>String(x),esc:x=>String(x),encName:x=>String(x),fmtSchedulerEta:x=>String(x),dgLevel:()=> 'ok'};
vm.createContext(ctx);
vm.runInContext(app.slice(app.indexOf('function dgRun(data)'),app.indexOf('function renderDiag(data)')),ctx);
vm.runInContext(fs.readFileSync('webui/metrics.js','utf8'),ctx);
const data={mode:'client',global_tx_packets:128,global_rx_packets:10,global_rx_bytes:1000,clients:{local:{tx_packets:125}},fec:{enabled:true,counter_domain:'written',data_tx:100,parity_tx:25,control_tx:3,data_wire_bytes:10000,parity_wire_bytes:2500},conns:[]};
ctx.renderConnQuality(data,null);
assert.equal(nodes['fec-overhead'].innerText,'25.0%');
assert.match(ctx.dgRun(data).fec.find(x=>x.ch==='fecovh').det,/^25\.0/);
assert.equal(ctx.dashboardQualityStats(data).avgPacketBytes,100);
const unequal=structuredClone(data);unequal.fec.parity_wire_bytes=5000;
assert.equal(ctx.dashboardQualityStats(unequal).fecOverheadPct,50,'byte ratio must account for variable frame sizes');
const legacy=structuredClone(data);delete legacy.fec.counter_domain;
assert.equal(ctx.dashboardQualityStats(legacy).fecOverheadPct,null,'unknown parity-attempt domain must not fabricate a wire ratio');
const zero=structuredClone(data);zero.fec.data_wire_bytes=0;
assert.equal(ctx.dashboardQualityStats(zero).fecOverheadPct,null);
const rows=[['a','A'],['b','A'],['c','B']].map(([conn_id,client_id])=>({conn_id,client_id,scheduler:{assigned_bytes:0,assigned_batches:0,fec_assigned_bytes:0,fec_assigned_batches:0}}));
const s={mode:'server',instance_id:'first',sample_time_ms:1000,server_conns:rows};ctx.renderConnsTable(s,true);
assert.equal(rows[0].scheduler._sampled,false);
s.sample_time_ms=2000;
rows.forEach((r,i)=>{r.scheduler.assigned_bytes=[1000,1000,8000][i];r.scheduler.assigned_batches=1;});ctx.renderConnsTable(s,true);
assert.deepEqual(rows.map(r=>r.scheduler._share_pct),[50,50,100]);
assert.equal(rows[0].scheduler._assign_bps,1000);
// FEC payload belongs to assignment traffic even on a DATA-standby path.
s.sample_time_ms=3000;rows[0].scheduler.fec_assigned_bytes=1000;rows[0].scheduler.fec_assigned_batches=1;ctx.renderConnsTable(s,true);
assert.equal(rows[0].scheduler._fec_assign_bps,1000);assert.equal(rows[0].scheduler._assign_bps,1000);
// An absent connection must not retain an old rate baseline.
s.sample_time_ms=4000;s.server_conns=rows.slice(1);ctx.renderConnsTable(s,true);
s.sample_time_ms=5000;s.server_conns=rows;ctx.renderConnsTable(s,true);assert.equal(rows[0].scheduler._sampled,false);
s.instance_id='second';s.sample_time_ms=1000;ctx.renderConnsTable(s,true);assert.equal(rows[1].scheduler._sampled,false);
Object.assign(ctx,{dashboardInstance:'first',dashboardUptime:100,globalPrev:{tx:5000},prev:{},lastT:42,prevPps:{ok:true},lastSpeeds:{},prevConns:{a:{}},lastConnsT:42,lastConnSpeeds:{a:{}},txHist:[1],rxHist:[2],txTimes:[3],trendData:{},logSeq:1000,evSeq:1000,evItems:[{}]});
vm.runInContext(app.slice(app.indexOf('function resetDashboardPeriod(data)')),ctx);
ctx.resetDashboardPeriod({instance_id:'second',uptime_sec:0});
assert.equal(ctx.logSeq,0);assert.equal(ctx.evSeq,0);assert.equal(ctx.lastT,0);assert.equal(ctx.lastConnsT,0);assert.equal(ctx.txHist.length,0);assert.equal(ctx.globalPrev,null);
console.log('WebUI metric regressions passed: byte-based FEC, shared diagnostic formula, per-session shares, FEC assignment, connection removal, process restart.');