/* Server-sampled diagnostic history. Null observations deliberately break lines. */
(function(){
  'use strict';
  const words={
    'zh-CN':['路径与开销趋势','客户端','连接','全部','各连接吞吐','各连接 RTT','调度负载','FEC 效果','Padding 开销','连接与异常','上行','下行','分配速率','队列积压','校验开销','恢复','未恢复','校验字节','填充字节','线路占比','在线连接','重连尝试','队列丢帧','TAP 写失败','等待服务端采样','与顶部时间范围同步；重启清空。每 2 秒采样，长范围按分钟聚合；无实测值处断线。最多保留每点 32 条连接，默认展示最近 8 条，可筛选历史连接。','采样连接数量已达上限','字节开销为本机发送，恢复/未恢复为本机接收；FEC 开销 = 校验 / DATA 字节，Padding 占比 = 填充 / 线路字节。','长范围：速率与 RTT 为区间均值，在线连接和队列也为均值；异常为每秒速率。'],
    'zh-TW':['路徑與開銷趨勢','用戶端','連線','全部','各連線吞吐','各連線 RTT','排程負載','FEC 效果','Padding 開銷','連線與異常','上行','下行','分配速率','佇列積壓','校驗開銷','恢復','未恢復','校驗位元組','填充位元組','線路占比','在線連線','重連嘗試','佇列丟幀','TAP 寫入失敗','等待伺服器採樣','與頂部時間範圍同步；重啟清空。每 2 秒採樣，長範圍按分鐘聚合；無實測值處斷線。每點最多 32 條連線，預設顯示最近 8 條，可篩選歷史連線。','採樣連線數量已達上限','位元組開銷為本機傳送，恢復/未恢復為本機接收；FEC 開銷 = 校驗 / DATA 位元組，Padding 占比 = 填充 / 線路位元組。','長範圍：速率、RTT、在線連線及佇列為區間均值；異常為每秒速率。'],
    en:['Path and overhead history','Client','Connection','All','Connection throughput','Connection RTT','Scheduler load','FEC effectiveness','Padding overhead','Connections and errors','Upload','Download','Assigned rate','Queued bytes','Parity overhead','Recovered','Unrecovered','Parity bytes','Padding bytes','Wire share','Online connections','Reconnect attempts','Backpressure drops','TAP write errors','Waiting for server samples','Uses the time range above; restart clears history. Samples every 2 seconds; long ranges use minute aggregates. Missing measurements break lines. Up to 32 connections per sample; the latest 8 are shown by default. Historical connections can be selected.','Sample connection limit reached','Byte overhead is local TX; recovery/loss is local RX. FEC overhead = parity / DATA bytes. Padding share = padding / wire bytes.','Long ranges: rates, RTT, online connections and queues are interval means; errors are rates per second.'],
    de:['Pfad- und Overhead-Verlauf','Client','Verbindung','Alle','Durchsatz je Verbindung','RTT je Verbindung','Scheduler-Last','FEC-Wirkung','Padding-Overhead','Verbindungen und Fehler','Upload','Download','Zuweisungsrate','Warteschlange','Paritäts-Overhead','Wiederhergestellt','Nicht wiederhergestellt','Paritätsbytes','Padding-Bytes','Leitungsanteil','Online-Verbindungen','Neuversuche','Warteschlangenverluste','TAP-Schreibfehler','Warten auf Server-Messwerte','Zeitraum wie oben; Neustart löscht den Verlauf. Messung alle 2 Sekunden, lange Bereiche als Minutenmittel. Fehlende Werte unterbrechen Linien. Bis 32 Verbindungen pro Messung; zuletzt 8 sichtbar, historische Verbindungen auswählbar.','Verbindungslimit erreicht','Byte-Overhead: lokaler TX; Wiederherstellung/Verlust: lokaler RX. FEC = Paritäts-/DATA-Bytes. Padding = Padding-/Leitungsbytes.','Lange Bereiche: Raten, RTT, Verbindungen und Warteschlangen sind Mittelwerte; Fehler pro Sekunde.'],
    fr:['Historique des chemins et surcoûts','Client','Connexion','Toutes','Débit par connexion','RTT par connexion','Charge de répartition','Efficacité FEC','Surcoût padding','Connexions et erreurs','Envoi','Réception','Débit affecté','Octets en attente','Surcoût parité','Récupérées','Non récupérées','Octets de parité','Octets de padding','Part du trafic','Connexions actives','Reconnexions tentées','Pertes de file','Erreurs écriture TAP','En attente des mesures serveur','Même période que ci-dessus ; historique effacé au redémarrage. Mesure toutes les 2 secondes, agrégation par minute pour les longues périodes. Les mesures absentes interrompent les courbes. Maximum 32 connexions par mesure ; les 8 dernières sont affichées, les anciennes peuvent être sélectionnées.','Limite de connexions atteinte','Octets : émission locale ; récupération/perte : réception locale. FEC = octets parité / DATA. Padding = octets padding / trafic.','Longues périodes : débits, RTT, connexions et files sont des moyennes ; erreurs par seconde.'],
    ja:['経路とオーバーヘッドの履歴','クライアント','接続','すべて','接続別スループット','接続別 RTT','スケジューラ負荷','FEC 効果','Padding オーバーヘッド','接続と異常','上り','下り','割当速度','待機バイト','パリティ比率','復元','未復元','パリティバイト','Padding バイト','通信量比率','オンライン接続','再接続試行','キュー破棄','TAP 書込エラー','サーバーの測定待ち','上部と同じ期間。再起動で履歴を消去。2 秒ごとに測定、長期間は分単位で集約。未測定箇所は線を切断。各測定は最大32接続、既定で最新8接続を表示。過去の接続も選択可能。','測定接続数の上限に達しました','バイト開銷はローカル送信、復元/未復元はローカル受信。FEC = パリティ / DATA バイト。Padding = Padding / 通信バイト。','長期間は速度、RTT、接続数、待機量の平均。異常は毎秒の発生率。']
  };
  const text=i=>(words[typeof LANG==='string'?LANG:'en']||words.en)[i];
  let history=null,hoverTime=null;
  const colors=['#6554ff','#08a579','#cf8200','#dc5478','#2589c7','#9868b8','#6e9835','#bd6940'];
  const section=document.createElement('section');section.className='card diagnostic-section';section.id='diagnostic-section';
  section.innerHTML='<div class="chart-head"><h2 class="card-title" id="diag-title"></h2><span id="diag-at" class="dim mono"></span><div class="seg" id="diag-range"><button data-v="2m" data-diag-range="2m"></button><button data-v="1h" data-diag-range="1h"></button><button data-v="24h" data-diag-range="24h"></button></div><label><span id="diag-client-label"></span> <select id="diag-client"></select></label><label><span id="diag-conn-label"></span> <select id="diag-conn"></select></label></div><p class="dim" id="diag-note"></p><p class="dim" id="diag-scope"></p><p class="dim" id="diag-aggregate"></p><p id="diag-limit" class="dim"></p><div class="diagnostic-grid">'+[4,5,6,7,8,9].map((title,i)=>'<article class="diagnostic-card"><h3 data-diag-title="'+title+'"></h3><div id="diag-body-'+i+'"></div></article>').join('')+'</div>';
  document.querySelector('.chart-card').after(section);
  const client=document.getElementById('diag-client'),conn=document.getElementById('diag-conn');
  function options(select,entries){const old=select.value;select.replaceChildren();[["",text(3)],...entries].forEach(([id,label])=>{const option=document.createElement('option');option.value=id;option.textContent=label;select.append(option);});if(entries.some(e=>e[0]===old))select.value=old;buildSelect(select);syncSelect(select);}
  function identities(){const ids=new Map();(history?.points||[]).forEach(p=>(p.conns||[]).forEach(c=>{ids.delete(c.id);ids.set(c.id,c);}));return [...ids.values()].reverse();}
  function updateOptions(){const ids=identities();options(client,[...new Set(ids.map(c=>c.client))].sort().map(id=>[id,id]));options(conn,ids.filter(c=>!client.value||c.client===client.value).map(c=>[c.id,c.client+' · '+c.label+' · '+c.id.slice(0,8)]));}
  function timeLabel(tick){return chartRange==='24h'?new Date(tick).toLocaleString(typeof LANG==='string'?LANG:'en',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):fmtHM(tick);}
  function labels(){document.getElementById('diag-title').textContent=text(0);document.getElementById('diag-client-label').textContent=text(1);document.getElementById('diag-conn-label').textContent=text(2);document.getElementById('diag-note').textContent=text(25);document.getElementById('diag-scope').textContent=text(27);document.getElementById('diag-aggregate').textContent=text(28);section.querySelectorAll('[data-diag-title]').forEach(el=>el.textContent=text(Number(el.dataset.diagTitle)));updateOptions();draw();}
  function format(v,unit){if(v==null)return '—';if(unit==='bytes')return fmtBytes(v,true);if(unit==='queue')return fmtBytes(v);return Number(v.toFixed(2))+(unit==='ms'?' ms':unit==='pct'?'%':unit==='rate'?'/s':'');}
  function panel(card,key,series,unit){
    const body=document.getElementById('diag-body-'+card);let wrap=document.getElementById('diag-wrap-'+key);
    if(!wrap){wrap=document.createElement('div');wrap.id='diag-wrap-'+key;wrap.innerHTML='<canvas id="diag-'+key+'" height="150"></canvas><div class="legend diagnostic-legend"></div>';body.append(wrap);const canvas=wrap.querySelector('canvas');canvas.addEventListener('pointermove',ev=>{const rect=canvas.getBoundingClientRect(),plot=canvas.diagPlot;if(!plot||!history?.points.length)return;const x=Math.max(0,Math.min(1,(ev.clientX-rect.left-plot.l)/(plot.r-plot.l)));const target=plot.first+x*(plot.last-plot.first);hoverTime=history.points.reduce((best,p)=>Math.abs(p.t-target)<Math.abs(best.t-target)?p:best).t;draw();});canvas.addEventListener('pointerleave',()=>{hoverTime=null;draw();});}
    const canvas=wrap.querySelector('canvas'),ctx=canvas.getContext('2d'),W=canvas.clientWidth||320,H=150,dpr=window.devicePixelRatio||1;
    canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.font='10px sans-serif';
    const pts=history?.points||[];let max=1;series.forEach(s=>pts.forEach(p=>{const v=s.value(p);if(v!=null&&Number.isFinite(v))max=Math.max(max,v);}));
    const ticks=[max,max/2,0].map(v=>format(v,unit));const L=Math.ceil(Math.max(...ticks.map(s=>ctx.measureText(s).width)))+14,R=12,T=12,B=24,pw=W-L-R,ph=H-T-B;
    const first=pts[0]?.t||0,last=pts[pts.length-1]?.t||first+1,x=t=>L+(t-first)/Math.max(1,last-first)*pw,y=v=>T+(1-v/max)*ph;
    canvas.diagPlot={l:L,r:W-R,first,last};ctx.textAlign='right';ticks.forEach((tick,i)=>{const yy=T+i*ph/2;ctx.strokeStyle=cssv('--grid');ctx.beginPath();ctx.moveTo(L,yy);ctx.lineTo(W-R,yy);ctx.stroke();ctx.fillStyle=cssv('--sub');ctx.fillText(tick,L-6,yy+3);});
    series.forEach((s,j)=>{ctx.strokeStyle=s.color||colors[j%colors.length];ctx.lineWidth=1.8;ctx.setLineDash(s.dash?[4,3]:[]);ctx.beginPath();let started=false,previous=0;pts.forEach(p=>{const v=s.value(p);if(v==null||!Number.isFinite(v)){started=false;return;}const xx=x(p.t),yy=y(v);if(!started||p.t-previous>(history.step_sec||2)*2500)ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy);started=true;previous=p.t;});ctx.stroke();ctx.setLineDash([]);});
    ctx.fillStyle=cssv('--sub');ctx.textAlign='center';(chartRange==='24h'?(pw<ctx.measureText(timeLabel(first)).width+ctx.measureText(timeLabel(last)).width+8?[1]:[0,1]):[0,0.5,1]).forEach(f=>{if(!pts.length)return;const label=timeLabel(first+f*(last-first));const tw=ctx.measureText(label).width;ctx.fillText(label,Math.max(L+tw/2,Math.min(L+f*pw,W-R-tw/2)),H-7);});
    const selected=pts.find(p=>p.t===hoverTime);canvas.dataset.diagHover=selected?String(selected.t):'';
    if(selected){ctx.strokeStyle=cssv('--sub');ctx.setLineDash([2,3]);ctx.beginPath();ctx.moveTo(x(selected.t),T);ctx.lineTo(x(selected.t),H-B);ctx.stroke();ctx.setLineDash([]);}
    if(!pts.length){ctx.textAlign='center';ctx.fillText(text(24),W/2,T+ph/2,W-16);}
    else if(!series.some(s=>pts.some(p=>s.value(p)!=null))){ctx.textAlign='center';ctx.fillText('—',W/2,T+ph/2);}
    const legend=wrap.querySelector('.legend');legend.replaceChildren();series.forEach((s,j)=>{const span=document.createElement('span'),dot=document.createElement('i');dot.className='dot';dot.style.background=s.color||colors[j%colors.length];span.append(dot,document.createTextNode(s.name+(selected?' '+format(s.value(selected),unit):'')));legend.append(span);});
  }
  function draw(){
    document.getElementById('diag-at').textContent=hoverTime?timeLabel(hoverTime):'';
    setSeg('diag-range',chartRange);section.querySelectorAll('[data-diag-range]').forEach(b=>b.textContent=t('chart.r'+b.dataset.diagRange));
    document.getElementById('diag-limit').textContent=history?.points.some(p=>p.truncated)?text(26):'';
    const ids=identities().filter(c=>(!client.value||c.client===client.value)&&(!conn.value||c.id===conn.value)).slice(0,8);
    const connectionSeries=(metric,label,dash=false)=>ids.map((c,i)=>({name:c.id.slice(0,8)+' '+text(label),color:colors[i],dash,value:p=>p.conns?.find(x=>x.id===c.id)?.metrics?.[metric]??null}));
    const metric=(key,label)=>({name:text(label),value:p=>p.metrics?.[key]??null});
    panel(0,'throughput',[...connectionSeries('up',10),...connectionSeries('down',11,true)],'bytes');
    panel(1,'rtt',connectionSeries('rtt',5),'ms');
    panel(2,'assigned',connectionSeries('assigned',12),'bytes');panel(2,'queue',connectionSeries('queue',13),'queue');
    panel(3,'fec-pct',[metric('fec_pct',14)],'pct');panel(3,'fec-recovery',[metric('recovered',15),metric('lost',16)],'rate');panel(3,'fec-parity',[metric('fec_parity',17)],'bytes');
    panel(4,'pad-rate',[metric('pad',18)],'bytes');panel(4,'pad-pct',[metric('pad_pct',19)],'pct');
    panel(5,'online',[metric('online',20)],'count');panel(5,'errors',[metric('reconnect',21),metric('drop',22),metric('tap_error',23)],'rate');
  }
  window.applyDiagnostics=function(data){if(!data||!Array.isArray(data.points))return;if(typeof dashboardInstance==='string'&&dashboardInstance&&data.instance_id!==dashboardInstance)return;history=data;hoverTime=null;updateOptions();draw();};
  document.getElementById('diag-range').addEventListener('click',ev=>{const button=ev.target.closest('[data-diag-range]');if(button)setRange(button.dataset.diagRange);});
  client.addEventListener('change',()=>{conn.value='';updateOptions();draw();});conn.addEventListener('change',draw);
  const oldRange=setRange;setRange=function(v){history=null;hoverTime=null;updateOptions();draw();return oldRange(v);};
  const oldStats=applyStats;applyStats=function(data){if(history&&data?.instance_id&&data.instance_id!==history.instance_id){history=null;hoverTime=null;updateOptions();draw();}return oldStats(data);};
  const oldI18n=applyI18n;applyI18n=function(){const out=oldI18n();labels();return out;};
  const oldTheme=applyTheme;applyTheme=function(){const out=oldTheme();draw();return out;};
  window.addEventListener('resize',draw);labels();
})();
