(() => {
  'use strict';
  const root=document.getElementById('pane-status');
  if(!root||document.getElementById('frameviz-card'))return;

  const lang=localStorage.getItem('tlsvpn_lang')||'zh-CN';
  const D={
    'zh-CN':{title:'帧格式示例',sub:'当前数据面协议 · 聚合写入 · 非实时抓包',example:'1514 B Ethernet 数据帧（启用内层 AEAD）',header:'10 B 帧头',cipher:'1514 B 密文',tag:'16 B AEAD Tag',tail:'仅 batch 尾帧可选 Padding',hdesc:'固定大端序：[dataLen:u32][padLen:u16][seq:u32]。本例 dataLen=1514+16=1530；普通数据帧 padLen=0；seq=42。',cdesc:'seq>0 时使用协商的内层 AEAD；AAD = dataLen(4B BE) || seq(4B BE)。',tdesc:'当前所有内层 AEAD 均使用 16 B 认证标签。',pdesc:'数据面不再逐帧 bucket padding。多个 TLSVPN 帧先聚合，只有 TLS plaintext batch 的最后一帧可能增加 padLen；padding 同时受 10% 有效 batch 字节和 512 B 上限限制。',batch:'TLS plaintext batch（软上限 12 KiB）',final:'Final frame · padLen=N',flow:'Ethernet → AEAD(+16B) → 10B TLSVPN header → 多帧聚合 → 尾帧可选 MSS 对齐 padding → TLS Write',note:'TLS plaintext 最大 16 KiB。seq=0 的握手/控制/心跳不使用内层 AEAD；独立控制帧仍可按 pad_mode 使用 bucket/off 填充。',nonce:'Nonce：AES-GCM / ChaCha20 = seq(4BE)||salt(8B)；XChaCha20 = 派生 20B prefix||seq(4BE)。'},
    'zh-TW':{title:'訊框格式範例',sub:'目前資料面協定 · 聚合寫入 · 非即時封包擷取',example:'1514 B Ethernet 資料幀（啟用內層 AEAD）',header:'10 B 訊框標頭',cipher:'1514 B 密文',tag:'16 B AEAD Tag',tail:'僅 batch 尾幀可選 Padding',hdesc:'固定大端序：[dataLen:u32][padLen:u16][seq:u32]。本例 dataLen=1530；一般資料幀 padLen=0；seq=42。',cdesc:'seq>0 時使用協商的內層 AEAD；AAD = dataLen(4B BE) || seq(4B BE)。',tdesc:'目前所有內層 AEAD 均使用 16 B 驗證標籤。',pdesc:'資料面不再逐幀 bucket padding。多個 TLSVPN 幀先聚合，只有 TLS plaintext batch 的最後一幀可能增加 padLen；padding 同時受 10% 有效 batch 位元組與 512 B 上限限制。',batch:'TLS plaintext batch（軟上限 12 KiB）',final:'Final frame · padLen=N',flow:'Ethernet → AEAD(+16B) → 10B TLSVPN header → 多幀聚合 → 尾幀可選 MSS 對齊 padding → TLS Write',note:'TLS plaintext 最大 16 KiB。seq=0 的握手/控制/心跳不使用內層 AEAD；獨立控制幀仍可依 pad_mode 使用 bucket/off 填充。',nonce:'Nonce：AES-GCM / ChaCha20 = seq(4BE)||salt(8B)；XChaCha20 = 衍生 20B prefix||seq(4BE)。'},
    en:{title:'Frame format example',sub:'Current data plane · aggregated writes · not a live capture',example:'1514 B Ethernet data frame with inner AEAD',header:'10 B header',cipher:'1514 B ciphertext',tag:'16 B AEAD tag',tail:'Optional padding on batch tail only',hdesc:'Fixed big-endian header: [dataLen:u32][padLen:u16][seq:u32]. Here dataLen=1514+16=1530; ordinary data frames use padLen=0; seq=42.',cdesc:'For seq>0 the negotiated inner AEAD is used. AAD = dataLen(4B BE) || seq(4B BE).',tdesc:'All current inner AEADs use a 16 B authentication tag.',pdesc:'The data plane no longer bucket-pads every frame. Frames are aggregated first; only the final frame of the TLS plaintext batch may receive padLen, bounded by both 10% of useful batch bytes and 512 B.',batch:'TLS plaintext batch (12 KiB soft limit)',final:'Final frame · padLen=N',flow:'Ethernet → AEAD(+16B) → 10B TLSVPN header → aggregate frames → optional MSS-alignment tail padding → TLS Write',note:'TLS plaintext is capped at 16 KiB. seq=0 handshake/control/heartbeat frames bypass inner AEAD; standalone control frames may still use bucket/off padding from pad_mode.',nonce:'Nonce: AES-GCM / ChaCha20 = seq(4BE)||salt(8B); XChaCha20 = derived 20B prefix||seq(4BE).'},
    de:{title:'Beispiel für Frame-Format',sub:'Aktueller Datenpfad · aggregierte Writes · kein Live-Mitschnitt',example:'1514-B-Ethernet-Datenframe mit innerem AEAD',header:'10-B-Header',cipher:'1514 B Chiffretext',tag:'16-B-AEAD-Tag',tail:'Optionales Padding nur am Batch-Ende',hdesc:'Fester Big-Endian-Header: [dataLen:u32][padLen:u16][seq:u32]. dataLen=1530; normale Datenframes nutzen padLen=0; seq=42.',cdesc:'Bei seq>0 wird das ausgehandelte innere AEAD verwendet. AAD = dataLen(4B BE) || seq(4B BE).',tdesc:'Alle aktuellen inneren AEADs verwenden einen 16-B-Authentifizierungs-Tag.',pdesc:'Datenframes werden zuerst aggregiert; nur der letzte Frame des TLS-Plaintext-Batches darf padLen erhalten. Das Padding ist auf 10% der Nutzdaten und 512 B begrenzt.',batch:'TLS-Plaintext-Batch (12 KiB Soft-Limit)',final:'Final frame · padLen=N',flow:'Ethernet → AEAD(+16B) → 10-B-TLSVPN-Header → Frames aggregieren → optionales MSS-Tail-Padding → TLS Write',note:'TLS-Plaintext ist auf 16 KiB begrenzt. seq=0 Handshake-/Control-/Heartbeat-Frames umgehen das innere AEAD.',nonce:'Nonce: AES-GCM / ChaCha20 = seq(4BE)||salt(8B); XChaCha20 = abgeleitetes 20B-Präfix||seq(4BE).'},
    fr:{title:'Exemple de format de trame',sub:'Plan de données actuel · écritures agrégées · pas une capture en direct',example:'Trame Ethernet 1514 o avec AEAD interne',header:'En-tête 10 o',cipher:'Chiffré 1514 o',tag:'Tag AEAD 16 o',tail:'Padding optionnel en fin de batch',hdesc:'En-tête big-endian : [dataLen:u32][padLen:u16][seq:u32]. dataLen=1530 ; les trames ordinaires utilisent padLen=0 ; seq=42.',cdesc:'Pour seq>0, l’AEAD interne négocié est utilisé. AAD = dataLen(4B BE) || seq(4B BE).',tdesc:'Tous les AEAD internes actuels utilisent un tag de 16 o.',pdesc:'Les trames sont d’abord agrégées ; seule la dernière trame du batch TLS en clair peut recevoir padLen, limité à 10% des octets utiles et à 512 o.',batch:'Batch TLS en clair (limite souple 12 KiB)',final:'Final frame · padLen=N',flow:'Ethernet → AEAD(+16B) → en-tête TLSVPN 10 o → agrégation → padding final MSS optionnel → TLS Write',note:'Le texte clair TLS est plafonné à 16 KiB. Les trames seq=0 de handshake/control/heartbeat n’utilisent pas l’AEAD interne.',nonce:'Nonce : AES-GCM / ChaCha20 = seq(4BE)||salt(8B) ; XChaCha20 = préfixe dérivé 20B||seq(4BE).'},
    ja:{title:'フレーム形式の例',sub:'現在のデータプレーン · 集約 Write · ライブキャプチャではありません',example:'内部 AEAD を使用する 1514 B Ethernet データフレーム',header:'10 B ヘッダー',cipher:'1514 B 暗号文',tag:'16 B AEAD タグ',tail:'batch 末尾のみ任意 Padding',hdesc:'固定ビッグエンディアン：[dataLen:u32][padLen:u16][seq:u32]。dataLen=1530、通常データは padLen=0、seq=42。',cdesc:'seq>0 ではネゴシエート済み内部 AEAD を使用します。AAD = dataLen(4B BE) || seq(4B BE)。',tdesc:'現在の内部 AEAD はすべて 16 B 認証タグを使用します。',pdesc:'データフレームを先に集約し、TLS plaintext batch の最後のフレームだけが padLen を持てます。padding は有効バイトの 10% と 512 B の両方で制限されます。',batch:'TLS plaintext batch（ソフト上限 12 KiB）',final:'Final frame · padLen=N',flow:'Ethernet → AEAD(+16B) → 10B TLSVPN header → 複数 frame 集約 → 任意の MSS tail padding → TLS Write',note:'TLS plaintext は最大 16 KiB。seq=0 の handshake/control/heartbeat は内部 AEAD を使用しません。',nonce:'Nonce：AES-GCM / ChaCha20 = seq(4BE)||salt(8B)；XChaCha20 = 派生 20B prefix||seq(4BE)。'}
  };
  const s=D[lang]||D.en;
  const card=document.createElement('div');
  card.id='frameviz-card';
  card.className='st-block frameviz-card';
  card.innerHTML=`
    <style>
      .frameviz-card{column-span:all;margin-top:4px}.fv-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-end;flex-wrap:wrap}.fv-sub{font-size:.78rem;color:var(--muted)}
      .fv-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:12px 0}.fv-mini,.fv-desc,.fv-batch{border:1px solid var(--border);border-radius:10px;padding:10px}.fv-mini span{display:block;color:var(--muted);font-size:.74rem}.fv-mini b{display:block;margin-top:4px;font:600 .91rem var(--mono,monospace)}
      .fv-track{display:flex;min-width:620px;min-height:72px;border:1px solid var(--border);border-radius:10px;overflow:hidden}.fv-seg{padding:10px 8px;border-right:1px solid var(--border);background:color-mix(in srgb,var(--card) 80%,var(--accent) 20%)}.fv-seg:last-child{border-right:0}.fv-seg b,.fv-seg small{display:block}.fv-seg small{margin-top:5px;color:var(--muted);font-family:var(--mono,monospace)}.fv-h{flex:0 0 18%}.fv-c{flex:1}.fv-t{flex:0 0 17%}.fv-p{flex:0 0 22%}
      .fv-descs{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:10px}.fv-desc{color:var(--muted);font-size:.8rem;line-height:1.45}.fv-desc b{display:block;color:var(--fg);margin-bottom:4px}.fv-batch{margin-top:10px}.fv-batch-row{display:flex;gap:5px;min-width:560px;margin-top:7px}.fv-batch-row span{flex:1;border:1px solid var(--border);border-radius:8px;padding:9px;text-align:center;font:12px var(--mono,monospace)}.fv-batch-row span:last-child{border-style:dashed}.fv-scroll{overflow-x:auto}.fv-flow,.fv-note{margin-top:9px;color:var(--muted);font-size:.79rem;line-height:1.5}.fv-flow{font-family:var(--mono,monospace);color:var(--fg)}
      @media(max-width:720px){.fv-kpis,.fv-descs{grid-template-columns:1fr 1fr}}
    </style>
    <div class="fv-head"><div><h3>${s.title}</h3><div class="fv-sub">${s.sub}</div></div><div class="fv-sub">${s.example}</div></div>
    <div class="fv-kpis"><div class="fv-mini"><span>header</span><b>10 B</b></div><div class="fv-mini"><span>dataLen</span><b>1530 B</b></div><div class="fv-mini"><span>padLen</span><b>0 B / tail N</b></div><div class="fv-mini"><span>batch</span><b>≤ 12 KiB soft</b></div></div>
    <div class="fv-scroll"><div class="fv-track"><div class="fv-seg fv-h"><b>${s.header}</b><small>dataLen | padLen | seq</small></div><div class="fv-seg fv-c"><b>${s.cipher}</b><small>Ethernet payload</small></div><div class="fv-seg fv-t"><b>${s.tag}</b><small>dataLen includes tag</small></div><div class="fv-seg fv-p"><b>${s.tail}</b><small>0..min(10%, 512 B)</small></div></div></div>
    <div class="fv-descs"><div class="fv-desc"><b>${s.header}</b>${s.hdesc}</div><div class="fv-desc"><b>${s.cipher}</b>${s.cdesc}</div><div class="fv-desc"><b>${s.tag}</b>${s.tdesc}</div><div class="fv-desc"><b>${s.tail}</b>${s.pdesc}</div></div>
    <div class="fv-batch"><div class="fv-sub">${s.batch}</div><div class="fv-scroll"><div class="fv-batch-row"><span>Frame #42 · padLen=0</span><span>Frame #43 · padLen=0</span><span>${s.final}</span></div></div></div>
    <div class="fv-flow">${s.flow}</div><div class="fv-note">${s.note}</div><div class="fv-note">${s.nonce}</div>`;
  const host=root.querySelector('.st-grid')||root.querySelector('.status-grid')||root;
  host.appendChild(card);
})();
