// Code-generated by the one-off WebUI parity migration.
// Keep assets local and embedded; do not replace these with CDN URLs.

pub fn asset(path: &str) -> Option<(&'static [u8], &'static str)> {
    match path {
        "/app.js" => Some((
            include_bytes!("../webui/app.js"),
            "application/javascript; charset=utf-8",
        )),
        "/favicon.ico" => Some((include_bytes!("../webui/favicon.ico"), "image/x-icon")),
        "/frameviz-zh-tw.js" => Some((
            include_bytes!("../webui/frameviz-zh-tw.js"),
            "application/javascript; charset=utf-8",
        )),
        "/frameviz.js" => Some((
            include_bytes!("../webui/frameviz.js"),
            "application/javascript; charset=utf-8",
        )),
        "/icons/arch-arm.svg" => Some((
            include_bytes!("../webui/icons/arch-arm.svg"),
            "image/svg+xml",
        )),
        "/icons/arch-arm64.svg" => Some((
            include_bytes!("../webui/icons/arch-arm64.svg"),
            "image/svg+xml",
        )),
        "/icons/arch-generic.svg" => Some((
            include_bytes!("../webui/icons/arch-generic.svg"),
            "image/svg+xml",
        )),
        "/icons/arch-loong64.svg" => Some((
            include_bytes!("../webui/icons/arch-loong64.svg"),
            "image/svg+xml",
        )),
        "/icons/arch-mips.svg" => Some((
            include_bytes!("../webui/icons/arch-mips.svg"),
            "image/svg+xml",
        )),
        "/icons/arch-riscv64.svg" => Some((
            include_bytes!("../webui/icons/arch-riscv64.svg"),
            "image/svg+xml",
        )),
        "/icons/arch-x86.svg" => Some((
            include_bytes!("../webui/icons/arch-x86.svg"),
            "image/svg+xml",
        )),
        "/icons/arch-x86_64.svg" => Some((
            include_bytes!("../webui/icons/arch-x86_64.svg"),
            "image/svg+xml",
        )),
        "/icons/os-android.svg" => Some((
            include_bytes!("../webui/icons/os-android.svg"),
            "image/svg+xml",
        )),
        "/icons/os-bsd.svg" => Some((include_bytes!("../webui/icons/os-bsd.svg"), "image/svg+xml")),
        "/icons/os-generic.svg" => Some((
            include_bytes!("../webui/icons/os-generic.svg"),
            "image/svg+xml",
        )),
        "/icons/os-linux.svg" => Some((
            include_bytes!("../webui/icons/os-linux.svg"),
            "image/svg+xml",
        )),
        "/icons/os-macos.svg" => Some((
            include_bytes!("../webui/icons/os-macos.svg"),
            "image/svg+xml",
        )),
        "/icons/os-windows.svg" => Some((
            include_bytes!("../webui/icons/os-windows.svg"),
            "image/svg+xml",
        )),
        "/" | "/index.html" => Some((
            include_bytes!("../webui/index.html"),
            "text/html; charset=utf-8",
        )),
        "/login" | "/login.html" => Some((
            include_bytes!("../webui/login.html"),
            "text/html; charset=utf-8",
        )),
        "/style.css" => Some((
            include_bytes!("../webui/style.css"),
            "text/css; charset=utf-8",
        )),
        "/zh-tw.js" => Some((
            include_bytes!("../webui/zh-tw.js"),
            "application/javascript; charset=utf-8",
        )),
        _ => None,
    }
}
